### Installing Dependencies

In [1]:
!pip install omegaconf==2.1.1 --quiet

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hydra-core 0.11.3 requires omegaconf<1.5,>=1.4, but you have omegaconf 2.1.1 which is incompatible.
whisperx 3.8.5 requires omegaconf>=2.3.0, but you have omegaconf 2.1.1 which is incompatible.

In [2]:
!pip install pyannote.audio==2.1.1 --quiet
!pip install speechbrain==0.5.16 --quiet

ERROR: Could not find a version that satisfies the requirement torchaudio<1.0,>=0.10 (from pyannote-audio) (from versions: 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0)
ERROR: No matching distribution found for torchaudio<1.0,>=0.10

In [3]:
!pip install whisperx --quiet

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hydra-core 0.11.3 requires omegaconf<1.5,>=1.4, but you have omegaconf 2.3.1 which is incompatible.

### Import Libraries

In [1]:
import os
import subprocess
import whisperx

C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\ctranslate2\__init__.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\speechbrain\utils\torch_audio_backend.py:22: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData

### Input file

In [2]:
audio_file = r"C:\Users\subha\Projects\Travenor\travenor-tests\test-subha.mp3"
print(os.path.exists(audio_file))

True

### Converting to WAV file

In [3]:
converted_wav = "converted10.wav"

command = [
    "ffmpeg",
    "-i", audio_file,
    "-ac", "1",
    "-ar", "16000",
    converted_wav,
    "-y"
]

subprocess.run(command)

print("Conversion completed!")

Conversion completed!

### Applying DeepFilterNet

In [4]:
import sys

deepfilter_command = [
    sys.executable,
    "-m",
    "df.enhance",
    "converted10.wav",
    "--output-dir",
    "cleaned"
]

subprocess.run(deepfilter_command)

print("Noise reduction completed!")

Noise reduction completed!

In [8]:
%pip uninstall -y transformers --quiet
%pip install transformers==4.44.2 --no-cache-dir --quiet

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\~6kenizers'.
  You can safely remove it manually.
  WARNING: The script transformers-cli.exe is installed in 'C:\Users\subha\anaconda3\envs\travenor\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
whisperx 3.3.1 requires pyannote.audio==3.3.2, but you have pyannote-audio 3.1.1 which is incompatible.

### Applying Whisper

In [9]:
cleaned_audio = r"C:/Users/subha/Projects/travenor-tests/cleaned/converted10_DeepFilterNet3.wav"

In [5]:
import torch
import whisperx
import os

# --- Define your audio path here ---
cleaned_audio = r"C:\Users\subha\Projects\Travenor\travenor-tests\cleaned\converted10_DeepFilterNet3.wav"

# Validate the file exists before doing anything
if not os.path.exists(cleaned_audio):
    raise FileNotFoundError(
        f"Audio file not found: {cleaned_audio}\n"
        f"Please check:\n"
        f"  1. The file path is correct\n"
        f"  2. The file was actually saved/generated by the previous step\n"
        f"  3. You're using the right filename and extension"
    )

print(f"Audio file found: {cleaned_audio}")

device = "cpu"

model = whisperx.load_model(
    "medium",
    device=device,
    compute_type="int8"
)

print("WhisperX model loaded!")
result = model.transcribe(cleaned_audio)
print("Transcription completed!")
print(result)

Audio file found: C:\Users\subha\Projects\Travenor\travenor-tests\cleaned\converted10_DeepFilterNet3.wav
No language specified, language will be first be detected for each audio file (increases inference time).

C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\whisperx\assets\pytorch_model.bin`

Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.5.1+cu121. Bad things might happen unless you revert torch to 1.x.
WhisperX model loaded!
Detected language: en (0.98) in first 30s of audio...
Transcription completed!
{'segments': [{'text': " Should we start? Yeah, start. Hey guys, what's up? Long time no see. Hello. Hello, bye. How are you? When are we going to Kashmir? All through December. In December, Kashmir?", 'start': 6.476, 'end': 34.787}, {'text': " Lots of snow will be there. Why not? But we are somehow, are we able to go in Kashmir after our this semester like in summer somehow? In summer Kerala is way better. Yeah, that's fine, but", 'start': 35.776, 'end': 65.589}, {'text': ' There are two types of beauty in Kashmir, like in summer, one type of beauty. I want to go to Kashmir and Kerala both. It will be more expensive. Summer, winter or summer.', 'start': 66.271, 'end': 81.203}, {'text': ' I think we should recall our Meghalaya memories where we went into the summer and then it was perfectly fine, summer and the monsoon. I think Kerala will be just like that. Okay, but I want to share my experience on Pangar Sula track. Can I share? Yes, sure.', 'start': 90.759, 'end': 115.964}, {'text': ' Yeah, it was a memorable journey. Firstly, we went to Rishikesh from our institute. Then we started our journey with a team from various destinations of India, like someone from Delhi, someone from Kashmir also. One of our seniors was here in Kashmir. And we went in Joshimath, which is situated', 'start': 118.234, 'end': 147.875}, {'text': ' Rishikesh, not nearby Rishikesh, 2, 1, 2 kilometers from Rishikesh. Then from Joshimath, we went to Karchi village. And then from there, Karchi village, our trek started. And after two days, we came back at Karchi village with lots of memories and something big was there.', 'start': 148.387, 'end': 173.49}, {'text': " So what is your plan? You guys are planning about Kashmir. Give me some ideas about Kashmir. If we can't make Kashmir because of our financial reasons, then we can go to Manali, I guess. Manali is more interesting than Kashmir. I must say Mizoram Trip was the best. OK. Yeah, Mizoram is so much better than anyone.", 'start': 177.995, 'end': 207.534}, {'text': " Hmm. These are people are exceptionally warm. Why not we are going together in Guwahati and planning some places in Guwahati like Jorhat. We should go to the next one. We can go to Nagaland and book more tickets. Yeah, it's far better than Guwahati. Aruna didn't went to Nagaland because of his health issue.", 'start': 208.251, 'end': 236.596}, {'text': " Yeah, that's my mistake as well. What was Nagal and Skeptics? It was good for you. You know, you read the Kedarnath track, so I don't think it will be any problem for you. And also, you have done Panchajuna. Oh my God. Oh my God. One of our fellow friends, Aniruddha Karmakar, is doing now a track. I don't know what that is. He tends to stay in the G4 desert.", 'start': 239.172, 'end': 267.961}], 'language': 'en'}

In [6]:
transcript = "" 
for segment in result["segments"]:
    print(segment["text"])
    transcript += segment["text"]

 Should we start? Yeah, start. Hey guys, what's up? Long time no see. Hello. Hello, bye. How are you? When are we going to Kashmir? All through December. In December, Kashmir?
 Lots of snow will be there. Why not? But we are somehow, are we able to go in Kashmir after our this semester like in summer somehow? In summer Kerala is way better. Yeah, that's fine, but
 There are two types of beauty in Kashmir, like in summer, one type of beauty. I want to go to Kashmir and Kerala both. It will be more expensive. Summer, winter or summer.
 I think we should recall our Meghalaya memories where we went into the summer and then it was perfectly fine, summer and the monsoon. I think Kerala will be just like that. Okay, but I want to share my experience on Pangar Sula track. Can I share? Yes, sure.
 Yeah, it was a memorable journey. Firstly, we went to Rishikesh from our institute. Then we started our journey with a team from various destinations of India, like someone from Delhi, someone from Kashmir also. One of our seniors was here in Kashmir. And we went in Joshimath, which is situated
 Rishikesh, not nearby Rishikesh, 2, 1, 2 kilometers from Rishikesh. Then from Joshimath, we went to Karchi village. And then from there, Karchi village, our trek started. And after two days, we came back at Karchi village with lots of memories and something big was there.
 So what is your plan? You guys are planning about Kashmir. Give me some ideas about Kashmir. If we can't make Kashmir because of our financial reasons, then we can go to Manali, I guess. Manali is more interesting than Kashmir. I must say Mizoram Trip was the best. OK. Yeah, Mizoram is so much better than anyone.
 Hmm. These are people are exceptionally warm. Why not we are going together in Guwahati and planning some places in Guwahati like Jorhat. We should go to the next one. We can go to Nagaland and book more tickets. Yeah, it's far better than Guwahati. Aruna didn't went to Nagaland because of his health issue.
 Yeah, that's my mistake as well. What was Nagal and Skeptics? It was good for you. You know, you read the Kedarnath track, so I don't think it will be any problem for you. And also, you have done Panchajuna. Oh my God. Oh my God. One of our fellow friends, Aniruddha Karmakar, is doing now a track. I don't know what that is. He tends to stay in the G4 desert.

### Diarization model

In [12]:
diarize_model = whisperx.DiarizationPipeline(
    device=device
)

print("Diarization model loaded!")

Diarization model loaded!

In [13]:
diarize_segments = diarize_model(cleaned_audio)

print("Diarization completed!")

C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\pyannote\audio\models\blocks\pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Diarization completed!

In [14]:
result = whisperx.assign_word_speakers(
    diarize_segments,
    result
)

print("Speakers assigned!")

Speakers assigned!

#### Speaker wise script assignment

In [15]:
for segment in result["segments"]:
    
    speaker = segment.get("speaker", "UNKNOWN")
    text = segment["text"]

    print(f"{speaker}: {text}")

SPEAKER_01:  Should we start? Yeah, start. Hey guys, what's up? Long time no see. Hello. Hello, bye. How are you? When are we going to Kashmir? All through December. In December, Kashmir?
SPEAKER_02:  Lots of snow will be there. Why not? But we are somehow, are we able to go in Kashmir after our this semester like in summer somehow? In summer Kerala is way better. Yeah, that's fine, but
SPEAKER_02:  There are two types of beauty in Kashmir, like in summer, one type of beauty. I want to go to Kashmir and Kerala both. It will be more expensive. Summer, winter or summer.
SPEAKER_01:  I think we should recall our Meghalaya memories where we went into the summer and then it was perfectly fine, summer and the monsoon. I think Kerala will be just like that. Okay, but I want to share my experience on Pangar Sula track. Can I share? Yes, sure.
SPEAKER_02:  Yeah, it was a memorable journey. Firstly, we went to Rishikesh from our institute. Then we started our journey with a team from various destinations of India, like someone from Delhi, someone from Kashmir also. One of our seniors was here in Kashmir. And we went in Joshimath, which is situated
SPEAKER_02:  Rishikesh, not nearby Rishikesh, 2, 1, 2 kilometers from Rishikesh. Then from Joshimath, we went to Karchi village. And then from there, Karchi village, our trek started. And after two days, we came back at Karchi village with lots of memories and something big was there.
SPEAKER_00:  So what is your plan? You guys are planning about Kashmir. Give me some ideas about Kashmir. If we can't make Kashmir because of our financial reasons, then we can go to Manali, I guess. Manali is more interesting than Kashmir. I must say Mizoram Trip was the best. OK. Yeah, Mizoram is so much better than anyone.
SPEAKER_03:  Hmm. These are people are exceptionally warm. Why not we are going together in Guwahati and planning some places in Guwahati like Jorhat. We should go to the next one. We can go to Nagaland and book more tickets. Yeah, it's far better than Guwahati. Aruna didn't went to Nagaland because of his health issue.
SPEAKER_03:  Yeah, that's my mistake as well. What was Nagal and Skeptics? It was good for you. You know, you read the Kedarnath track, so I don't think it will be any problem for you. And also, you have done Panchajuna. Oh my God. Oh my God. One of our fellow friends, Aniruddha Karmakar, is doing now a track. I don't know what that is. He tends to stay in the G4 desert.

In [ ]:
pip install "transformers==4.46.3"

## Location Extraction

In [ ]:
%pip uninstall transformers gliner -y
%pip install "transformers==4.46.3" gliner --quiet

In [ ]:
%pip uninstall transformers gliner huggingface_hub -y
%pip install "huggingface_hub==0.24.7" "transformers==4.46.3" "gliner==0.2.13" --quiet

In [7]:
from gliner import GLiNER

In [8]:
model = GLiNER.from_pretrained(
    "urchade/gliner_medium-v2.1"
)

labels = [
    # Geography
    "location",
    "place",
    "city",
    "state",
    "country",
    "village",
    "tourist destination",
    "mountain",
    "trek",
    "region",
    
    # Natural Tourist Spots
    "beach", "mountain", "national park", "lake", "island",
    
    # Built Tourist Spots
    "temple", "museum", "monument", "historical site",
    
    # Catch-all for other specific attractions (e.g., "Eiffel Tower")
    "tourist attraction"
]
entities = model.predict_entities(
    transcript,
    labels
)

for e in entities:
    print(e)

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\transformers\convert_slow_tokenizer.py:561: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
C:\Users\subha\anaconda3\envs\travenor\Lib\site-packages\gliner\data_processing\processor.py:269: UserWarning: Sentence of length 540 has been truncated to 384
  warnings.warn(f"Sentence of length {len(tokens)} has been truncated to {max_len}")
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'start': 123, 'end': 130, 'text': 'Kashmir', 'label': 'city', 'score': 0.5486559867858887}
{'start': 167, 'end': 174, 'text': 'Kashmir', 'label': 'city', 'score': 0.5682185888290405}
{'start': 254, 'end': 261, 'text': 'Kashmir', 'label': 'city', 'score': 0.5559821724891663}
{'start': 320, 'end': 326, 'text': 'Kerala', 'label': 'state', 'score': 0.9009714126586914}
{'start': 398, 'end': 405, 'text': 'Kashmir', 'label': 'city', 'score': 0.5483892560005188}
{'start': 459, 'end': 466, 'text': 'Kashmir', 'label': 'city', 'score': 0.5824252367019653}
{'start': 471, 'end': 477, 'text': 'Kerala', 'label': 'state', 'score': 0.9061923623085022}
{'start': 566, 'end': 575, 'text': 'Meghalaya', 'label': 'state', 'score': 0.5394531488418579}
{'start': 679, 'end': 685, 'text': 'Kerala', 'label': 'state', 'score': 0.8506062030792236}
{'start': 949, 'end': 954, 'text': 'India', 'label': 'country', 'score': 0.9641712307929993}
{'start': 994, 'end': 1001, 'text': 'Kashmir', 'label': 'city', 'score': 0.5979095697402954}
{'start': 1039, 'end': 1046, 'text': 'Kashmir', 'label': 'city', 'score': 0.5322909355163574}
{'start': 1063, 'end': 1072, 'text': 'Joshimath', 'label': 'village', 'score': 0.9111836552619934}
{'start': 1092, 'end': 1101, 'text': 'Rishikesh', 'label': 'city', 'score': 0.5390107035636902}
{'start': 1114, 'end': 1123, 'text': 'Rishikesh', 'label': 'city', 'score': 0.5099696516990662}
{'start': 1149, 'end': 1158, 'text': 'Rishikesh', 'label': 'city', 'score': 0.5381602644920349}
{'start': 1170, 'end': 1179, 'text': 'Joshimath', 'label': 'village', 'score': 0.867838442325592}
{'start': 1192, 'end': 1206, 'text': 'Karchi village', 'label': 'village', 'score': 0.971981406211853}
{'start': 1229, 'end': 1243, 'text': 'Karchi village', 'label': 'village', 'score': 0.9765541553497314}
{'start': 1249, 'end': 1253, 'text': 'trek', 'label': 'trek', 'score': 0.8972954750061035}
{'start': 1299, 'end': 1313, 'text': 'Karchi village', 'label': 'village', 'score': 0.972299337387085}
{'start': 1415, 'end': 1422, 'text': 'Kashmir', 'label': 'city', 'score': 0.5498143434524536}
{'start': 1449, 'end': 1456, 'text': 'Kashmir', 'label': 'city', 'score': 0.5819525718688965}
{'start': 1475, 'end': 1482, 'text': 'Kashmir', 'label': 'city', 'score': 0.5525598526000977}
{'start': 1535, 'end': 1541, 'text': 'Manali', 'label': 'village', 'score': 0.8085017800331116}
{'start': 1552, 'end': 1558, 'text': 'Manali', 'label': 'village', 'score': 0.8188260793685913}
{'start': 1584, 'end': 1591, 'text': 'Kashmir', 'label': 'city', 'score': 0.5911314487457275}

In [9]:
destinations = [entity["text"] for entity in entities]

unique_destinations = list(dict.fromkeys(destinations))

print(unique_destinations)

['Kashmir', 'Kerala', 'Meghalaya', 'India', 'Joshimath', 'Rishikesh', 'Karchi village', 'trek', 'Manali']

## Generating Cluster

In [ ]:
%pip install networkx python-louvain matplotlib --quiet

In [10]:
from geopy.geocoders import Nominatim
import pandas as pd
import time

In [11]:
geolocator = Nominatim(user_agent="travel_recommender")
locations = []

In [12]:
for place in destinations:

    try:
        location = geolocator.geocode(place)

        if location:
            locations.append({
                "name": place,
                "latitude": location.latitude,
                "longitude": location.longitude
            })

        time.sleep(1)

    except Exception as e:
        print(place, e)

In [13]:
extracted_locations = pd.DataFrame(locations)

extracted_locations

              name   latitude  longitude
0          Kashmir  26.264420  71.602750
1          Kashmir  26.264420  71.602750
2          Kashmir  26.264420  71.602750
3           Kerala  10.352874  76.512040
4          Kashmir  26.264420  71.602750
5          Kashmir  26.264420  71.602750
6           Kerala  10.352874  76.512040
7        Meghalaya  25.537943  91.299910
8           Kerala  10.352874  76.512040
9            India  22.351115  78.667743
10         Kashmir  26.264420  71.602750
11         Kashmir  26.264420  71.602750
12       Joshimath  30.555575  79.561261
13       Rishikesh  30.108654  78.291619
14       Rishikesh  30.108654  78.291619
15       Rishikesh  30.108654  78.291619
16       Joshimath  30.555575  79.561261
17  Karchi village  30.483037  79.607738
18  Karchi village  30.483037  79.607738
19            trek  54.609811  18.800229
20  Karchi village  30.483037  79.607738
21         Kashmir  26.264420  71.602750
22         Kashmir  26.264420  71.602750
23         Kashmir  26.264420  71.602750
24          Manali  32.245461  77.187293
25          Manali  32.245461  77.187293
26         Kashmir  26.264420  71.602750

### Visualization on map

In [ ]:
%pip install folium

In [14]:
import folium

In [15]:
center_lat = extracted_locations.latitude.mean()
center_lon = extracted_locations.longitude.mean()

m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=7
)

for _, row in extracted_locations.iterrows():

    folium.Marker(
        [row.latitude, row.longitude],
        popup=row.name
    ).add_to(m)

m

In [16]:
import numpy as np
from sklearn.cluster import DBSCAN

coords = np.array(
    list(
        zip(
            extracted_locations.latitude,
            extracted_locations.longitude
        )
    )
)

In [17]:
kms_per_radian = 6371.0088

epsilon = 100 / kms_per_radian

db = DBSCAN(
    eps=epsilon,
    min_samples=1,
    metric="haversine"
)

labels = db.fit_predict(
    np.radians(coords)
)

In [18]:
extracted_locations["cluster"] = labels

extracted_locations

              name   latitude  longitude  cluster
0          Kashmir  26.264420  71.602750        0
1          Kashmir  26.264420  71.602750        0
2          Kashmir  26.264420  71.602750        0
3           Kerala  10.352874  76.512040        1
4          Kashmir  26.264420  71.602750        0
5          Kashmir  26.264420  71.602750        0
6           Kerala  10.352874  76.512040        1
7        Meghalaya  25.537943  91.299910        2
8           Kerala  10.352874  76.512040        1
9            India  22.351115  78.667743        3
10         Kashmir  26.264420  71.602750        0
11         Kashmir  26.264420  71.602750        0
12       Joshimath  30.555575  79.561261        4
13       Rishikesh  30.108654  78.291619        5
14       Rishikesh  30.108654  78.291619        5
15       Rishikesh  30.108654  78.291619        5
16       Joshimath  30.555575  79.561261        4
17  Karchi village  30.483037  79.607738        4
18  Karchi village  30.483037  79.607738        4
19            trek  54.609811  18.800229        6
20  Karchi village  30.483037  79.607738        4
21         Kashmir  26.264420  71.602750        0
22         Kashmir  26.264420  71.602750        0
23         Kashmir  26.264420  71.602750        0
24          Manali  32.245461  77.187293        7
25          Manali  32.245461  77.187293        7
26         Kashmir  26.264420  71.602750        0

In [19]:
tour_groups = {}

for cluster_id in extracted_locations["cluster"].unique():

    places = extracted_locations[
        extracted_locations["cluster"] == cluster_id
    ]["name"].tolist()

    tour_groups[cluster_id] = places

tour_groups

{0: ['Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir',
  'Kashmir'],
 1: ['Kerala', 'Kerala', 'Kerala'],
 2: ['Meghalaya'],
 3: ['India'],
 4: ['Joshimath',
  'Joshimath',
  'Karchi village',
  'Karchi village',
  'Karchi village'],
 5: ['Rishikesh', 'Rishikesh', 'Rishikesh'],
 6: ['trek'],
 7: ['Manali', 'Manali']}

In [20]:
print(python)

NameError: name 'python' is not defined